"""Workflow helpers for the rebuilt media-manager core."""

from .catalog import (
    WorkflowDefinition,
    WorkflowProblem,
    get_workflow_definition,
    get_workflow_problem,
    list_workflow_problems,
    list_workflows,
)
from .cleanup import (
    CleanupExecutionReport,
    CleanupWorkflowOptions,
    CleanupWorkflowReport,
    DEFAULT_CLEANUP_RENAME_TEMPLATE,
    build_cleanup_workflow_report,
    execute_cleanup_workflow,
)
from .forms import (
    WorkflowFormField,
    WorkflowFormModel,
    build_workflow_form_model,
    list_workflow_form_models,
)
from .gui_shell import (
    GuiShellModel,
    GuiShellProblemCard,
    GuiShellWorkflowCard,
    build_gui_shell_model,
    build_shell_command_preview_for_problem,
    build_shell_command_preview_for_workflow,
)
from .presets import (
    WorkflowPreset,
    WorkflowProfile,
    WorkflowProfileValidation,
    build_workflow_profile_argv,
    build_workflow_profile_payload,
    get_workflow_preset,
    list_workflow_presets,
    load_workflow_profile,
    render_workflow_preset_command,
    render_workflow_profile_command,
    save_workflow_profile,
    validate_workflow_profile,
)
from .trip import (
    TripDryRun,
    TripExecutionEntry,
    TripExecutionResult,
    TripPlanEntry,
    TripWorkflowOptions,
    build_trip_dry_run,
    execute_trip_plan,
    parse_trip_date,
)
from .wizard import WorkflowCommandSuggestion, WorkflowWizardResult, build_workflow_wizard_result

__all__ = [
    "WorkflowDefinition",
    "WorkflowProblem",
    "list_workflows",
    "get_workflow_definition",
    "list_workflow_problems",
    "get_workflow_problem",
    "WorkflowFormField",
    "WorkflowFormModel",
    "build_workflow_form_model",
    "list_workflow_form_models",
    "GuiShellWorkflowCard",
    "GuiShellProblemCard",
    "GuiShellModel",
    "build_gui_shell_model",
    "build_shell_command_preview_for_workflow",
    "build_shell_command_preview_for_problem",
    "WorkflowPreset",
    "WorkflowProfile",
    "WorkflowProfileValidation",
    "build_workflow_profile_argv",
    "build_workflow_profile_payload",
    "list_workflow_presets",
    "get_workflow_preset",
    "load_workflow_profile",
    "render_workflow_preset_command",
    "render_workflow_profile_command",
    "save_workflow_profile",
    "validate_workflow_profile",
    "WorkflowCommandSuggestion",
    "WorkflowWizardResult",
    "build_workflow_wizard_result",
    "CleanupExecutionReport",
    "CleanupWorkflowOptions",
    "CleanupWorkflowReport",
    "DEFAULT_CLEANUP_RENAME_TEMPLATE",
    "build_cleanup_workflow_report",
    "execute_cleanup_workflow",
    "TripWorkflowOptions",
    "TripPlanEntry",
    "TripDryRun",
    "TripExecutionEntry",
    "TripExecutionResult",
    "parse_trip_date",
    "build_trip_dry_run",
    "execute_trip_plan",
]
